
name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: '30 11,23 * * *' # 每天 UTC 时间 11/30,23/30 执行一次
  push:
    branches:
      - main
jobs:
  visit-url:
    runs-on: ubuntu-latest
    env:
      URL1: ${{ secrets.URL_1 }}
      URL2: ${{ secrets.URL_2 }}
    steps:
      - name: Visit URL 1
        run: curl $URL1
      - name: Visit URL 2
        run: curl $URL2
